deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Vercel
        run: npx vercel --prod --token=${{ secrets.VERCEL_TOKEN }} --scope=guiiholi513-9406s-projects
        env:
          VERCEL_PROJECT_ID: prj_ldw5lccUE9fyJtanC8ZsOWMzClqV